# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(140, 140, 651, 192))
        self.listWidget.setObjectName("listWidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 64, 16))
        self.label_3.setObjectName("label_3")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(140, 440, 134, 28))
        self.start.setObjectName("start")
        self.choose_file = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file.setGeometry(QtCore.QRect(22, 10, 111, 28))
        self.choose_file.setObjectName("choose_file")
        self.file_path = QtWidgets.QTextEdit(self.centralwidget)
        self.file_path.setGeometry(QtCore.QRect(140, 10, 651, 31))
        self.file_path.setObjectName("file_path")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 431, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.checkbox_noun = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkbox_noun.setObjectName("checkbox_noun")
        self.horizontalLayout.addWidget(self.checkbox_noun)
        self.checkbox_adjective = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkbox_adjective.setObjectName("checkbox_adjective")
        self.horizontalLayout.addWidget(self.checkbox_adjective)
        self.checkbox_verb = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkbox_verb.setObjectName("checkbox_verb")
        self.horizontalLayout.addWidget(self.checkbox_verb)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 90, 166, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.message = QtWidgets.QListWidget(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(140, 340, 651, 91))
        self.message.setObjectName("message")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 340, 72, 16))
        self.label_4.setObjectName("label_4")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(700, 440, 93, 28))
        self.save_button.setObjectName("save_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Результат:"))
        self.start.setText(_translate("MainWindow", "Анализировать файл"))
        self.choose_file.setText(_translate("MainWindow", "Путь к файлу"))
        self.label.setText(_translate("MainWindow", "Часть речи:"))
        self.checkbox_noun.setText(_translate("MainWindow", "Существительные"))
        self.checkbox_adjective.setText(_translate("MainWindow", "Прилагательные"))
        self.checkbox_verb.setText(_translate("MainWindow", "Глаголы"))
        self.label_2.setText(_translate("MainWindow", "Слов в результате:"))
        self.label_4.setText(_translate("MainWindow", "Ход работы:"))
        self.save_button.setText(_translate("MainWindow", "Сохранить"))
