# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 342)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(140, 50, 42, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99)
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 108, 16))
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(140, 90, 651, 141))
        self.listWidget.setObjectName("listWidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 61, 16))
        self.label_3.setObjectName("label_3")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(140, 300, 134, 28))
        self.start.setObjectName("start")
        self.choose_file = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file.setGeometry(QtCore.QRect(22, 10, 111, 28))
        self.choose_file.setObjectName("choose_file")
        self.file_path = QtWidgets.QTextEdit(self.centralwidget)
        self.file_path.setGeometry(QtCore.QRect(140, 10, 651, 31))
        self.file_path.setObjectName("file_path")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(330, 39, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_noun = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_noun.setObjectName("checkBox_noun")
        self.horizontalLayout.addWidget(self.checkBox_noun)
        self.checkBox_verb = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_verb.setObjectName("checkBox_verb")
        self.horizontalLayout.addWidget(self.checkBox_verb)
        self.checkBox_adjective = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_adjective.setObjectName("checkBox_adjective")
        self.horizontalLayout.addWidget(self.checkBox_adjective)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 42, 61, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(290, 300, 371, 28))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.messages = QtWidgets.QListWidget(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(140, 250, 651, 31))
        self.messages.setObjectName("messages")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 250, 64, 31))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Слов в результате:"))
        self.label_3.setText(_translate("MainWindow", "Результат:"))
        self.start.setText(_translate("MainWindow", "Анализировать файл"))
        self.choose_file.setText(_translate("MainWindow", "Путь к файлу"))
        self.checkBox_noun.setText(_translate("MainWindow", "Существительные"))
        self.checkBox_verb.setText(_translate("MainWindow", "Глаголы"))
        self.checkBox_adjective.setText(_translate("MainWindow", "Прилагательные"))
        self.label.setText(_translate("MainWindow", "Часть речи:"))
        self.label_4.setText(_translate("MainWindow", "Ход работы:"))
